# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "on [$hostname](bold purple) "
trim_at = "."
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[:](bold cyan)"
error_symbol = "[X :](bold red)"

[directory]
read_only = " [X] "
truncation_length = 10
truncate_to_repo = true
style = "bold italic cyan"

[git_branch]
format = "[git:\\([$branch](bold red)\\)]($style) "

[git_state]
style = "bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "REBASE"
merge = "MERGE"
revert = "REVERT"
cherry_pick = "CHERRY"
bisect = "BISECT"
am = "AM"
am_or_rebase = "AM/REBASE"

[git_status]
style = "bold cyan"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false