#! /bin/env bash

DMENU="dmenu -i -l 20 -sb #9600fa -p"

DMTERM="alacritty -e"

DMEDITOR="emacsclient -c -a ''"

SCREEN_LOCKER="slock"

BROWSER="firefox"

declare -A config_edit_list
config_edit_list[config defaults]="$HOME/scripts/dmscripts/config-defaults"
config_edit_list[doom emacs init.el]="$HOME/.config/doom/init.el"
config_edit_list[doom emacs config.el]="$HOME/.config/doom/config.el"
config_edit_list[vim]="$HOME/.vimrc"
config_edit_list[lunar vim]="$HOME/.config/lvim/config.lua"
config_edit_list[alacritty]="$HOME/.config/alacritty/alacritty.yml"
config_edit_list[zsh]="$HOME/.zshrc"
config_edit_list[fish]="$HOME/.config/fish/config.fish"
config_edit_list[bash]="$HOME/.bashrc"
config_edit_list[qtile]="$HOME/.config/qtile/config.py"
config_edit_list[qtile autostart]="$HOME/.config/qtile/autostart.sh"

declare -A brightness_values
brightness_values[100]="100"
brightness_values[200]="200"
brightness_values[300]="300"
brightness_values[400]="500"
brightness_values[500]="500"
brightness_values[600]="600"
brightness_values[700]="700"
brightness_values[800]="800"
brightness_values[900]="900"
brightness_values[1000]="1000"
brightness_values[2000]="2000"
brightness_values[3000]="3000"
brightness_values[4000]="4000"
brightness_values[4650]="4650"
brightness_values[quit]="quit"
