#! /bin/env bash

source $HOME/scripts/dmscripts/config-defaults

declare -a options=(
"Lock screen"
"Reboot"
"Shutdown"
"Quit"
)

choice=$(printf '%s\n' "${options[@]}" | ${DMENU} 'Shutdown menu:')

case $choice in
  'Lock screen')
    ${SCREEN_LOCKER}
    ;;

  'Reboot')
    if [[ "$(echo -e "No\nYes" | ${DMENU} "$choice?")" == "Yes" ]]; then
      systemctl reboot
    else
      exit 1
    fi
    ;;
  'Shutdown')
    if [[ "$(echo -e "No\nYes" | ${DMENU} "$choice?")" == "Yes" ]]; then
      systemctl poweroff
    else
      exit 1
    fi
    ;;
  'Quit')
      exit 1
    ;;

  *)
    exit 0
  ;;
esac
